### ISSUE TITLE
Configure a user to access Parse Dashboard remotely

### ISSUE THREAD

**Issue by Zenuncl** [yongjhih/docker-parse-dashboard#11]
After passing a ENV with User1 and User1_password, this still cannot work

```
docker run -d \
             -e APP_ID=$(APP_ID)\
             -e MASTER_KEY=$(MASTER_KEY)\
             -e SERVER_URL=http://localhost:1337/parse \
             -e PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1  \
             -e USER1=yourUsername  \
             -e USER1_PASSWORD=yourUsernamesPassword \
             -p 4040:4040                      \
             --link parse-server               \
             --name parse-dashboard            \
             yongjhih/parse-dashboard
```

**Comment by rahimrahman** [comment]
@SharkIng I used `PARSE_DASHBOARD_CONFIG` instead and able to make this work:

```
docker run -d \
            -e PARSE_DASHBOARD_CONFIG='{"apps":[{"appId":"<appid>","serverURL":"<docker-ip>/parse","masterKey":"<masterkey>","appName":"<appname>"}],"users":[{"user":"<username>","pass":"<password>"}]}' \
            -e PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1  \
            -p 4040:4040                      \
            --link parse-server               \
            --name parse-dashboard            \
            yongjhih/parse-dashboard
```

**Comment by jaimeagudo** [comment]
A bit more readable 
`parse-dashboard-config.json`
```
{
    "apps": [{
        "appId": "<appid>",
        "serverURL": "<docker-ip>/parse",
        "masterKey": "<masterkey>",
        "appName": "<appname>"
    }],
    "users": [{
        "user": "<username>",
        "pass": "<password>"
    }]
}
```

```
docker run -d \
            -e PARSE_DASHBOARD_CONFIG=`cat parse-dashboard-config.json`
            -e PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1  \
            -p 4040:4040                      \
            --link parse-server               \
            --name parse-dashboard            \
            yongjhih/parse-dashboard
```

**Comment by tigpt** [comment]
I'm trying to configure parse-dashboard with composer and jwilder/nginx-proxy and I'm getting the same error.

Does anyone had configured parse dashboard do access remotely successfully ?

Here is my docker-compose
```
parse-dashboard:
    image: yongjhih/parse-dashboard
    container_name: prase-dashboard
    environment:
      - VIRTUAL_HOST=[MYDOMAIN.COM]
      - PARSE_DASHBOARD_TRUST_PROXY=1
    volumes:
      - /root/parse-dashboard/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
      - /root/parse-dashboard/icons:/src/Parse-Dashboard/icons
```
then I access https://[MYDOMAIN.COM] and I get "Configure a user to access Parse Dashboard remotely".
Is there any option to be set on the users to enable remoce access ? Is this a generic error for something else? how to debug it?

Thanks
